Python Functions
--

In [52]:
import pandas as pd
import numpy as np

In [ ]:
x = 1
y = 2
z = 3

def mult(x,y,z):
    return x*y*z

mult(1,2,3)

In [9]:
def add_numbers(x, y, z):
    return x + y + z

print(add_numbers(1, 2, 5))

8


No need to set typing

No need to return anything

Can have default values for parameters

You can set a flag value and set as True or False

Finally you can assign a function to a variable and pass it to another function

In [12]:
def do_math(a, b, kind = 'add'):
    if (kind == 'add'):
        return a+b
    else:
        return a-b

In [13]:
do_math(1, 2, 'add')

3

In [16]:
do_math(1, 2, 'not add')

-1

Python Types and Sequences
---

In [20]:
# Tuples are immutable and appear in parenthesis. 
# Both lists and tuples are iterable objects

type('this is a string')

str

In [21]:
type(None)

NoneType

In [22]:
type(1)

int

In [23]:
type(1.0)

float

In [24]:
type(add_numbers)

function

In [26]:
x=(1, 'a', 2, 'b')
type(x)

tuple

In [35]:
# Lists are mutable and use square brackets. 
# Both lists and tuples are iterable objects

# Concatenate with +
# Get length with len
# Built in functions like sum(), max(), mean(), std(), var()
# Slicing with indexes is foundational to Python

x = 'This is a string'
print(x[0])
print(x[0:1])
print(x[0:3])

T
T
Thi


In [43]:
print(x[-1])
print(x[-4:-2])
print(x[:3])
print(x[3:])

g
ri
Thi
s is a string


In [39]:
x[-4:-2]

'ri'

In [45]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + '' + lastname)
print(firstname * 3)
print(f'Chris' in firstname)

ChristopherBrooks
ChristopherChristopherChristopher
True


In [34]:
x = 'Dr. Christopher Brooks'

print(x[4:15])

Christopher


In [50]:
# Split based on substrings - Regular Expressions dealt with in Text Mining

firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0]
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[3]
print(firstname + ' ' + lastname)

Christopher Brooks


In [52]:
# Dictionaries are labelled collections which do not have an order
# You need to assign a key to each value to retrieve the value from the dictionary

x = {'Christopher Brooks' : 'brooksch@umich.edu',
    'Bill Gates' : 'billg@microsoft.com'}

x['Christopher Brooks']

'brooksch@umich.edu'

In [53]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

In [56]:
# Iterating over the values in a dictionary

for email in x.values():
    print (email)

brooksch@umich.edu
billg@microsoft.com
None


In [57]:
for name in x:
    print (name)

Christopher Brooks
Bill Gates
Kevyn Collins-Thompson


In [59]:
for name, email in x.items():
    print(name, email)

Christopher Brooks brooksch@umich.edu
Bill Gates billg@microsoft.com
Kevyn Collins-Thompson None


In [63]:
# Unpacking in multiple variable assignments

x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email, location = x
print(fname)
print(lname)
print(email)
print(location)

# to unpack this you need to match the variable names to the contents of the variable

Christopher
Brooks
brooksch@umich.edu
Ann Arbor


Python String Files
---

In [68]:
# UTF8 has been introduced to create a universal language translation. Python uses this by default so no need to worry about Latin-1 etc

# print('Chris' + 2)

In [69]:
print('Chris' + str(2))

Chris2


In [80]:
## Here we setup a dictionary and apply string formatting to produce an outcome including variable operations

sales_record = {'price' : 3.24,
               'num_items' : 4,
               'person' : 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items'] * sales_record ['price']))

Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


Reading and Writing CSV Files
---

In [2]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

In [4]:
mpg[:3]

[OrderedDict([('', '1'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'auto(l5)'),
              ('drv', 'f'),
              ('cty', '18'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '2'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '1.8'),
              ('year', '1999'),
              ('cyl', '4'),
              ('trans', 'manual(m5)'),
              ('drv', 'f'),
              ('cty', '21'),
              ('hwy', '29'),
              ('fl', 'p'),
              ('class', 'compact')]),
 OrderedDict([('', '3'),
              ('manufacturer', 'audi'),
              ('model', 'a4'),
              ('displ', '2'),
              ('year', '2008'),
              ('cyl', '4'),
              ('trans', 'manual(m6)'),
              ('drv',

In [5]:
len(mpg) # We have a dictionary for each of 234 cars in the file

234

In [11]:
print(mpg[0].keys())
print(mpg[0].items())
print(mpg[0].values())

odict_keys(['', 'manufacturer', 'model', 'displ', 'year', 'cyl', 'trans', 'drv', 'cty', 'hwy', 'fl', 'class'])
odict_items([('', '1'), ('manufacturer', 'audi'), ('model', 'a4'), ('displ', '1.8'), ('year', '1999'), ('cyl', '4'), ('trans', 'auto(l5)'), ('drv', 'f'), ('cty', '18'), ('hwy', '29'), ('fl', 'p'), ('class', 'compact')])
odict_values(['1', 'audi', 'a4', '1.8', '1999', '4', 'auto(l5)', 'f', '18', '29', 'p', 'compact'])


In [15]:
# If we want to find the average city mpg across all the values in the dictionary

sum(float(d['cty']) for d in mpg) / len(mpg) # Here we are calculating the average city mpg for all dictionaries 

16.86

In [16]:
sum(float(d['hwy']) for d in mpg) / len(mpg) # Here we are calculating the average city mpg for all dictionaries 

23.44

In [20]:
# Let;s create a set within the dictionary to identify the unique cylinders in the dictionary

cylinders = set(car['cyl'] for car in mpg)
print(cylinders)

{'4', '5', '6', '8'}


In [21]:
# Now we will run a more complicated example - Summarising data through iteration
# Pandas will provide an easier and more efficient way of performing the same tasks using Map, Apply and various DataFrame operations


CtyMpgByCyl = [] # Here we setup an empty list and we will iterate to fill this list up

for c in cylinders:
    summpg = 0
    cyltypecount = 0
    for d in mpg:
        if d['cyl'] == c:
            summpg += float(d['cty'])
            cyltypecount += 1
    CtyMpgByCyl.append((c, summpg / cyltypecount))
    
CtyMpgByCyl.sort(key = lambda x: x[0])
CtyMpgByCyl

[('4', 21.01), ('5', 20.50), ('6', 16.22), ('8', 12.57)]

In [22]:
vehicleclass = set(d['class'] for d in mpg)
print(vehicleclass)

{'pickup', 'suv', 'minivan', 'subcompact', 'midsize', 'compact', '2seater'}


In [29]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes in the dataset
    summpg = 0
    vclasscount = 0
    for d in mpg:
        if d['class'] == t: # if the class matches the type t
            summpg += float(d['hwy']) # 
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')
    
HwyMpgByClass.sort(key = lambda x: x[1])
HwyMpgByClass

[('pickup', 16.88),
 ('suv', 18.13),
 ('minivan', 22.36),
 ('2seater', 24.80),
 ('midsize', 27.29),
 ('subcompact', 28.14),
 ('compact', 28.30)]

Dates and Times
---

In [1]:
#Some of the basics of timeseries
# Common legacy method is based on Jan 1, 1970 - historical reasons why this is the way
# transactions often stored in seconds and milliseconds from this data

In [7]:
import datetime as dt
import time as tm

ERROR: Could not find a version that satisfies the requirement time (from versions: none)
ERROR: No matching distribution found for time


In [8]:
tm.time()

1586853933.568278

In [10]:
# Create a variable using the from timestamp method in date time. 
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow 

datetime.datetime(2020, 4, 14, 10, 46, 39, 977665)

In [17]:
print(dtnow.year)
print(dtnow.month)
print(dtnow.day)
print(dtnow.hour)
print(dtnow.minute)
print(dtnow.second)
print(dtnow.microsecond)

2020
4
14
10
46
39
977665


In [27]:
# Set delta 100

delta100 = dt.timedelta(days = 100)
print(delta100)

100 days, 0:00:00


In [28]:
# Set today

today = dt.date.today()
print(today-delta100)

2020-01-05


In [30]:
today < today-delta100

False

Advanced Python Objects: Map
---

In [35]:
# This is not a course about object oriented programming but some concepts are very important to learn

# you can define a class using the class keyword and anything below this falls within the scope of the class
# Use Camel Case
# Dont declare variables - just use them
# Define a method but you must include Self in the method signaure
# You need to refer to variables but also need Self first
# Attributes of class via dot notation
# Can add a constructor but not obliatory __init__


class Person:
    department = 'School of Information'
    
    def set_name(self, new_name):
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location
    def set_mobile_number(self, mobile_number):
        self.location = mobile_number
    def set_email(self, email):
        self.email = email
      

#### Map is the basis for Functional Programming

Explicitly declare all parameters that will change when you call a function
Python is not a pure functional programming language because you can have many side effects and you can put many types of parameters in. You need to think carefully about how you chain operations together. Often a parameter for a function can be a function itself.


#### map(function, iterable, ...)
##### Return an iterator that applies function to every item of iterable, yielding the results. If additional iterable arguments are passed, function must take that many arguments and is applied to the items from all iterables in parallel. With multiple iterables, the iterator stops when the shortest iterable is exhausted. For cases where the function inputs are already arranged into argument tuples, see itertools.starmap().••

In [55]:
# Example of Map being used to iterate over two different lists to return a preset function output

store1 = [10., 11., 12.34, 2.34]
store2 = [9.0, 11.1, 12.34, 2.01]

cheapest = map(min, store1, store2)
cheapest # It is a lazy function - it allows very efficient memory management
print(list(cheapest))

dearest = map(max, store1, store2)
dearest
print(list(dearest))

[9.0, 11.0, 12.34, 2.01]
[10.0, 11.1, 12.34, 2.34]


In [113]:
# Here there is a function to split the names below into Title and Last Name. I will add First Name to it too

people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']

def split_title_and_name(person):
    title = person.split()[0]
    firstname = person.split()[1]
    lastname = person.split()[2]
    return '{} {} {}'.format(title, firstname, lastname)

#uple(map(split_title_and_name, people))
list(map(split_title_and_name, people))

['Dr. Christopher Brooks',
 'Dr. Kevyn Collins-Thompson',
 'Dr. VG Vinod',
 'Dr. Daniel Romero']

Advanced Python Lambda and List Comprehension
---

In [135]:
# Declare a lambda function with lambda
import math
a = 100
b = 10
my_function = lambda a,b,c : (a * b / c)
my_function(a,b,c)


-111.11111111111111

In [180]:
# Convert this function into a Lambda expression - Option 1

people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']


def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[2]

for person in people:
    print(split_title_and_name(person)) == (lambda x : x.split()[0] + '' + x.split()[2])(person)
        


Dr. Brooks
Dr. Collins-Thompson
Dr. Vinod
Dr. Romero


In [181]:
# Convert this function into a Lambda expression - Option 2

people = ['Dr. Christopher Brooks', 'Dr. Kevyn Collins-Thompson', 'Dr. VG Vinod Vydiswaran', 'Dr. Daniel Romero']


def split_title_and_name(person):
    return person.split()[0] + ' ' + person.split()[2]

list(map(lambda person: person.split()[0] + ' ' + person.split()[-1], people))

['Dr. Brooks', 'Dr. Collins-Thompson', 'Dr. Vydiswaran', 'Dr. Romero']

List Comprehensions
---

In [213]:
my_list = []
for number in range(0,1000):
    if number % 2 == 1:
        my_list.append(number)

print(np.array(my_list))

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

In [212]:
# Replace the standard for loop with a list comprehension
# Object For Object in Range If Object meets Condition

my_list = [number for number in range(0,1000) if number % 2 >= 1]
print(np.array(my_list))

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199 201 203 205 207 209 211 213 215
 217 219 221 223 225 227 229 231 233 235 237 239 241 243 245 247 249 251
 253 255 257 259 261 263 265 267 269 271 273 275 277 279 281 283 285 287
 289 291 293 295 297 299 301 303 305 307 309 311 313 315 317 319 321 323
 325 327 329 331 333 335 337 339 341 343 345 347 349 351 353 355 357 359
 361 363 365 367 369 371 373 375 377 379 381 383 385 387 389 391 393 395
 397 399 401 403 405 407 409 411 413 415 417 419 421 423 425 427 429 431
 433 435 437 439 441 443 445 447 449 451 453 455 457 459 461 463 465 467
 469 471 473 475 477 479 481 483 485 487 489 491 49

In [240]:
def times_tables(): # refine the function name and parameters
    lst = [] # create an empty list and fill it 
    for i in range(10): # Iterate i over range 0-9
        for j in range (10): # Iterate j over range 0-9
            lst.append(i*j) # Add to the list by taking the product of i and j
    return lst # Return the list

print(times_tables())

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81]


In [238]:
times_tables = [i * j for i in range(10) for j in range(10)]
print(times_tables)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81]


In [255]:
''' 

Here’s a harder question which brings a few things together.

Many organizations have user ids which are constrained in some way. 

Imagine you work at an internet service provider and the user ids are all two letters followed by two numbers (e.g. aa49). 

Your task at such an organization might be to hold a record on the billing activity for each possible user.

Write an initialization line as a single list comprehension which creates a list of all possible user ids. 

Assume the letters are all lower case.

'''

lowercase = 'abcdefghijklmnopqrstuvwxyz'
digits = '0123456789'


#Solution is to assign a variable to the first and second letter and a number to digit 1 and digit 2. By concatenating these you can iterate through the list fully
correct_answer = [let1 + let2 + num1 + num2 for let1 in lowercase for let2 in lowercase for num1 in digits for num2 in digits]

print(correct_answer[301:522]) # Display first 50 ids


['ad01', 'ad02', 'ad03', 'ad04', 'ad05', 'ad06', 'ad07', 'ad08', 'ad09', 'ad10', 'ad11', 'ad12', 'ad13', 'ad14', 'ad15', 'ad16', 'ad17', 'ad18', 'ad19', 'ad20', 'ad21', 'ad22', 'ad23', 'ad24', 'ad25', 'ad26', 'ad27', 'ad28', 'ad29', 'ad30', 'ad31', 'ad32', 'ad33', 'ad34', 'ad35', 'ad36', 'ad37', 'ad38', 'ad39', 'ad40', 'ad41', 'ad42', 'ad43', 'ad44', 'ad45', 'ad46', 'ad47', 'ad48', 'ad49', 'ad50', 'ad51', 'ad52', 'ad53', 'ad54', 'ad55', 'ad56', 'ad57', 'ad58', 'ad59', 'ad60', 'ad61', 'ad62', 'ad63', 'ad64', 'ad65', 'ad66', 'ad67', 'ad68', 'ad69', 'ad70', 'ad71', 'ad72', 'ad73', 'ad74', 'ad75', 'ad76', 'ad77', 'ad78', 'ad79', 'ad80', 'ad81', 'ad82', 'ad83', 'ad84', 'ad85', 'ad86', 'ad87', 'ad88', 'ad89', 'ad90', 'ad91', 'ad92', 'ad93', 'ad94', 'ad95', 'ad96', 'ad97', 'ad98', 'ad99', 'ae00', 'ae01', 'ae02', 'ae03', 'ae04', 'ae05', 'ae06', 'ae07', 'ae08', 'ae09', 'ae10', 'ae11', 'ae12', 'ae13', 'ae14', 'ae15', 'ae16', 'ae17', 'ae18', 'ae19', 'ae20', 'ae21', 'ae22', 'ae23', 'ae24', 'ae25',

Numpy
---

In [256]:
import numpy as np

In [259]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [261]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [269]:
m = np.array([[7,8,9], [10,11,23]]) # nested arrays / lists create a matrix or 2 dimensional array
m

array([[ 7,  8,  9],
       [10, 11, 23]])

In [270]:
m.shape

(2, 3)

In [272]:
n = np.arange(0,30,3)
n

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [276]:
n = n.reshape(5, 2)
n

array([[ 0,  3],
       [ 6,  9],
       [12, 15],
       [18, 21],
       [24, 27]])

In [279]:
n.resize(2,5)
n

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

In [281]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [282]:
np.zeros([9,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [285]:
np.eye(6,10) #

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]])

In [292]:
np.diag(x+y*22) #Note how the values are broadcast within the diagonal array

array([[ 89,   0,   0],
       [  0, 112,   0],
       [  0,   0, 135]])

In [293]:
np.array([1,2,3,4,5]*5)

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2,
       3, 4, 5])

In [295]:
p = np.ones([2,3], int); p

array([[1, 1, 1],
       [1, 1, 1]])

In [300]:
np.vstack([p, p+2, p+2**2]) #interesting - p = 1 + 2*2 (not 3**2)

array([[1, 1, 1],
       [1, 1, 1],
       [3, 3, 3],
       [3, 3, 3],
       [5, 5, 5],
       [5, 5, 5]])

In [302]:
np.stack([p, p+2, p+2**2])

array([[[1, 1, 1],
        [1, 1, 1]],

       [[3, 3, 3],
        [3, 3, 3]],

       [[5, 5, 5],
        [5, 5, 5]]])

Numpy Array Operations
---

In [311]:
print(x+y); 
print(x*y); 
print(x**2)
print(x.dot(y));
z = np.array([y, y**3])
print(z)

[5 7 9]
[ 4 10 18]
[1 4 9]
32
[[  4   5   6]
 [ 64 125 216]]


In [317]:
z.shape

(2, 3)

In [318]:
z.T.shape

(3, 2)

In [319]:
z.dtype

dtype('int64')

In [323]:
z = z.astype('float64')
z.dtype

dtype('float64')

In [325]:
a = np.array([-1, -2, 1, 3,5])
a.sum()

6

In [332]:
a.min()

-2

In [333]:
a.max()

5

In [327]:
a.mean()

1.2

In [329]:
a.std()

2.5612496949731396

In [330]:
a.argmax()

4

In [331]:
a.argmin()

1

Indexing and Slicing
---

In [337]:
s = np.arange(0,20) **2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [345]:
s[0], s[3], s[8], s[0:7], s[::4], s[-4]

(0,
 9,
 64,
 array([ 0,  1,  4,  9, 16, 25, 36]),
 array([  0,  16,  64, 144, 256]),
 256)

In [346]:
s[-4:] # Count from four from the end of the array to the end of the array

array([256, 289, 324, 361])

In [347]:
s[-5::-2] # Start at -5 so 225 and work back to start in steps of negative 2

array([225, 169, 121,  81,  49,  25,   9,   1])

In [348]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [354]:
# Select 7
r[1,1]

#Select 13-16
r[2, 1:5]

# Select cub right from 14
r[2:6, 2:6]

array([[14, 15, 16, 17],
       [20, 21, 22, 23],
       [26, 27, 28, 29],
       [32, 33, 34, 35]])

In [363]:
# Conditional Indexing

r[r != 13];
r[r >= 22]

array([22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [376]:
r[r >= 22] = 22 # Here we are assigning a new value to all integers with a value of 22 or higher
r

array([[ 1,  1,  1,  3,  4,  5],
       [ 1,  1,  1,  9, 10, 11],
       [ 1,  1,  1, 15, 16, 17],
       [18, 19, 20, 21, 22, 22],
       [22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22]])

In [375]:
# Create a new array which is a slice of r

r2 = r[:3,:3]
r2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [372]:
r2[:] = 1
r2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [378]:
# Create a copy
r_copy = r.copy()
r_copy = 10
r_copy

10

In [381]:
old = np.array([[1, 1, 1],
                [1, 1, 1]])

new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


# Iterate over arrays

In [388]:
test = np.random.randint(0, 10, (4,3))
test

array([[0, 6, 9],
       [5, 3, 9],
       [4, 7, 3],
       [6, 7, 4]])

In [390]:
for row in test:
    print (row)

[0 6 9]
[5 3 9]
[4 7 3]
[6 7 4]


In [394]:
for i in test:
    print (i)

[0 6 9]
[5 3 9]
[4 7 3]
[6 7 4]


In [395]:

for i in range(len(test)):
    print(test[i])

[0 6 9]
[5 3 9]
[4 7 3]
[6 7 4]


In [398]:

for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [0 6 9]
row 1 is [5 3 9]
row 2 is [4 7 3]
row 3 is [6 7 4]


In [404]:
test2 = test **2
print(test2)

[[ 0 36 81]
 [25  9 81]
 [16 49  9]
 [36 49 16]]


In [406]:
test3 = test2 * 3e-2
test3

array([[0.  , 1.08, 2.43],
       [0.75, 0.27, 2.43],
       [0.48, 1.47, 0.27],
       [1.08, 1.47, 0.48]])

In [419]:
for i, j, k in zip(test, test2, test3):
    print(np.ceil(i+j*k))

[  0.  45. 206.]
[ 24.   6. 206.]
[12. 80.  6.]
[45. 80. 12.]


In [420]:
['a', 'b', 'c'] + [1, 2, 3]

['a', 'b', 'c', 1, 2, 3]

In [421]:
type(lambda x: x+1)

function

In [432]:
r = np.arange(0,36)
r.reshape(6,6)

array([[0, 1, 2, 3, 4, 5]])

In [426]:
type(lambda x: x+1)

function

In [427]:
r.reshape(36)[::7]

array([ 0,  7, 14, 21, 28, 35])

In [431]:
r2 = r.reshape(36)[::6]
r2

array([ 0,  6, 12, 18, 24, 30])

In [433]:
r = np.arange(0,36)
r.reshape(36)
r[]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [448]:
r = np.arange(0,36)
r.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])